apiVersion: v1
kind: ServiceList
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: %APPNAME%
    spec:
      selector:
        app: %APPNAME%
      type: NodePort
      ports:
        - port: 80
          targetPort: 80
